"""Utilities for storing trading rules and strategies."""
import json
from typing import Any, List, Sequence

from .db_connections import ConnectionManager

CREATE_RULES_SQL = """
CREATE TABLE IF NOT EXISTS rules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    definition TEXT NOT NULL
)
"""

CREATE_STRATEGIES_SQL = """
CREATE TABLE IF NOT EXISTS strategies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    rule_ids TEXT NOT NULL
)
"""

CREATE_BACKTESTS_SQL = """
CREATE TABLE IF NOT EXISTS backtests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_id INTEGER NOT NULL,
    start_date TEXT,
    end_date TEXT,
    result TEXT NOT NULL,
    FOREIGN KEY(strategy_id) REFERENCES strategies(id)
)
"""


def initialize_db(conn_manager: ConnectionManager) -> None:
    """
    Creates the database tables for trading rules, strategies, and backtests if they do not exist.
    
    Initializes the required schema by executing SQL statements to create the `rules`, `strategies`, and `backtests` tables within a managed database connection.
    """
    with conn_manager.context() as conn:
        conn.execute(CREATE_RULES_SQL)
        conn.execute(CREATE_STRATEGIES_SQL)
        conn.execute(CREATE_BACKTESTS_SQL)
        conn.commit()


def add_rule(name: str, definition: str, conn_manager: ConnectionManager) -> int:
    """
    Inserts a new trading rule into the database and returns its autogenerated ID.
    
    Args:
        name: The name of the trading rule.
        definition: The definition or logic of the trading rule.
    
    Returns:
        The ID of the newly inserted rule.
    """
    with conn_manager.context() as conn:
        cur = conn.execute(
            "INSERT INTO rules (name, definition) VALUES (?, ?)",
            (name, definition),
        )
        conn.commit()
        return int(cur.lastrowid)


def list_rules(conn_manager: ConnectionManager) -> List[dict]:
    """
    Retrieves all trading rules from the database.
    
    Returns:
        A list of dictionaries, each containing the 'id', 'name', and 'definition' of a rule.
    """
    with conn_manager.context() as conn:
        cur = conn.execute("SELECT id, name, definition FROM rules")
        return [dict(row) for row in cur.fetchall()]


def add_strategy(name: str, rule_ids: Sequence[int], conn_manager: ConnectionManager) -> int:
    """
    Adds a new trading strategy with the specified name and associated rule IDs.
    
    Verifies that all provided rule IDs exist in the database before creating the strategy. Raises a ValueError if any rule IDs are missing.
    
    Args:
        name: The name of the strategy.
        rule_ids: A sequence of rule IDs to associate with the strategy.
    
    Returns:
        The autogenerated ID of the newly created strategy.
    
    Raises:
        ValueError: If any of the provided rule IDs do not exist.
    """
    # Verify all rule IDs exist
    with conn_manager.context() as conn:
        qs = ",".join("?" * len(rule_ids))
        cur = conn.execute(
            f"SELECT id FROM rules WHERE id IN ({qs})",
            tuple(rule_ids),
        )
        found_ids = {row["id"] for row in cur.fetchall()}
        missing = set(rule_ids) - found_ids
        if missing:
            raise ValueError(f"Unknown rule IDs: {sorted(missing)}")

    with conn_manager.context() as conn:
        cur = conn.execute(
            "INSERT INTO strategies (name, rule_ids) VALUES (?, ?)",
            (name, json.dumps(list(rule_ids))),
        )
        conn.commit()
        return int(cur.lastrowid)


def list_strategies(conn_manager: ConnectionManager) -> List[dict]:
    """
    Retrieves all trading strategies from the database.
    
    Returns:
        A list of dictionaries, each containing the strategy's id, name, and a list of associated rule IDs.
    """
    with conn_manager.context() as conn:
        cur = conn.execute("SELECT id, name, rule_ids FROM strategies")
        rows = cur.fetchall()
        return [dict(id=row[0], name=row[1], rule_ids=json.loads(row[2])) for row in rows]


def record_backtest(
    strategy_id: int,
    start_date: str,
    end_date: str,
    result: Any,
    conn_manager: ConnectionManager,
) -> int:
    """
    Records a backtest result for a given strategy.
    
    Inserts a new entry into the `backtests` table with the specified strategy ID, start and end dates, and a JSON-encoded result.
    
    Args:
        strategy_id: The ID of the strategy associated with the backtest.
        start_date: The start date of the backtest period.
        end_date: The end date of the backtest period.
        result: The backtest result data to be stored (will be JSON-encoded).
    
    Returns:
        The autogenerated ID of the new backtest record.
    """
    with conn_manager.context() as conn:
        cur = conn.execute(
            "INSERT INTO backtests (strategy_id, start_date, end_date, result) VALUES (?, ?, ?, ?)",
            (strategy_id, start_date, end_date, json.dumps(result)),
        )
        conn.commit()
        return int(cur.lastrowid)


def list_backtests(conn_manager: ConnectionManager) -> List[dict]:
    """
    Retrieves all backtest records from the database.
    
    Returns:
        A list of dictionaries, each containing the backtest's id, strategy_id, start_date, end_date, and result (decoded from JSON).
    """
    with conn_manager.context() as conn:
        cur = conn.execute(
            "SELECT id, strategy_id, start_date, end_date, result FROM backtests"
        )
        rows = cur.fetchall()
        return [
            {
                "id": row[0],
                "strategy_id": row[1],
                "start_date": row[2],
                "end_date": row[3],
                "result": json.loads(row[4]),
            }
            for row in rows
        ]
